name: CI/CD Pipeline

on:
  push:
    branches:
      - meenakshi
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest  
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
       fail-fast: false
       matrix:
        language: [ 'java', 'javascript' ]

    steps:
      # Stage 1: Git Clone
      - name: Checkout Code
        uses: actions/checkout@v4

      # Stage 2: Image Build
      - name: Build Frontend Docker Image
        run: docker build -t chattingo-frontend:latest ./frontend

      - name: Build Backend Docker Image
        run: docker build -t chattingo-backend:latest ./backend

      # Stage 3: Filesystem Scan (Static Code Analysis)
      - name: Run Code Scan
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # 👇 Add build step for Java (Maven example)
      - if: matrix.language == 'java'
        name: Build with Maven
        working-directory: ./backend
        run: mvn -B clean install -DskipTests

      # Stage 4: Image Scan (Trivy for vulnerabilities)
      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: chattingo-frontend:latest

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: chattingo-backend:latest

      # Stage 5: Push to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Frontend Image
        uses: docker/build-push-action@v4
        with:
         context: ./frontend
         push: true
         #tags: ${{ secrets.DOCKER_USERNAME }}/chattingo-frontend:latest
         tags: meenakshirawat/chattingo-frontend:latest 

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
         context: ./backend
         push: true
         #tags: ${{ secrets.DOCKER_USERNAME }}/chattingo-frontend:latest
         tags: meenakshirawat/chattingo-backend:latest

      # Stage 6: Update docker-compose.yml with new tags (example step)
      - name: Update Docker Compose
        run: |
          #sed -i "s|image: myrepo/frontend.*|image: myrepo/frontend:latest|g" docker-compose.yml
          #sed -i "s|image: myrepo/backend.*|image: myrepo/backend:latest|g" docker-compose.yml

          #sed -i "s|image: chattingo-frontend.*|image: chattingo-frontend:latest|g" docker-compose.yml
          #sed -i "s|image: chattingo-backend.*|image: chattingo-backend:latest|g" docker-compose.yml

      # Stage 7: Deploy to VPS (via SSH)
     
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          #host: ${{ secrets.VPS_HOST }}
          #username: ${{ secrets.VPS_USER }}
          host: 72.60.111.168
          username: root
         # key: ${{ secrets.VPS_SSH_KEY }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
             cd /root/chattingo
             git pull origin meenakshi
             docker-compose pull
             #docker-compose up -d
             docker-compose --env-file .env up -d

    
